### ISSUE TITLE
Error in cat("Result for", partlist[[sid]], ":", results, "\n") 

### ISSUE THREAD

**Issue by xush6528** [rchampoux/coursera#2]
I tried to run your version of submit code

got an error

```
Enter one or more numbers separated by spaces, or an empty line to cancel
1: 1 2 3 4
Error in cat("Result for", partlist[[sid]], ":", results, "\n") : 
  object 'partlist' not found
```

I switch to the original version and submitted successfully.
so I am sure I entered my account correctly

**Comment by rchampoux** [comment]
Not sure why some people get this error and others don't, but should be fixed now.  Thanks!
